import os
import glob
from pathlib import Path
from datetime import datetime

# Configuration
SOURCE_DIR = Path.home() / "Documents"
LOG_DIR = Path.home() / "Documents/AILogbooks/logs"
DELETION_LOG = LOG_DIR / f"{datetime.now().strftime('%m-%d')}_LOGS_SYS_Deletion-Report_AILogbooks.md"

# Files flagged for deletion from audit log
DEPRECATED_FILES = [
    "ConductChartScript_Proj_EdAssist_2026-01-11.docx",
    "Proj_EdAssist_MathBellringers.pptx",
    "Proj_EdAssist_2026-01-02_Doc_EurekaScopeSeq.pdf",
    "FLAIM_OperationsDashboard_v2.json",
    "FLAIM Drive Tracker.xlsx",
    "FilenamingMasterDatabase.gsheet"
]

def find_and_delete_deprecated():
    """Locate and delete deprecated files from Documents folder."""

    print("🗑️  DELETION PROCESS INITIATED")
    print("=" * 50)

    deleted_files = []
    not_found = []

    for filename in DEPRECATED_FILES:
        print(f"\n🔍 Searching for: {filename}")

        # Search for the file in Documents
        pattern = str(SOURCE_DIR / f"**/{filename}")
        matches = glob.glob(pattern, recursive=True)

        # Filter out AILogbooks folder
        matches = [m for m in matches if "AILogbooks" not in m]

        if matches:
            for file_path in matches:
                try:
                    os.remove(file_path)
                    print(f"   ✅ DELETED: {file_path}")
                    deleted_files.append({
                        "name": filename,
                        "path": file_path,
                        "timestamp": datetime.now()
                    })
                except Exception as e:
                    print(f"   ❌ ERROR: Could not delete {file_path}: {e}")
        else:
            print(f"   ⚠️  NOT FOUND (may have been already deleted or moved)")
            not_found.append(filename)

    # Generate deletion report
    generate_deletion_report(deleted_files, not_found)

    print("\n" + "=" * 50)
    print(f"📊 SUMMARY:")
    print(f"   Files Deleted: {len(deleted_files)}")
    print(f"   Files Not Found: {len(not_found)}")
    print(f"   Deletion Log: {DELETION_LOG}")

    return deleted_files, not_found

def generate_deletion_report(deleted, not_found):
    """Generate markdown report of deletion activity."""

    LOG_DIR.mkdir(parents=True, exist_ok=True)

    with open(DELETION_LOG, 'w') as f:
        f.write(f"# 🗑️ File Deletion Report\n")
        f.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Action:** Cleanup of deprecated/duplicate files\n\n")

        f.write("## ✅ Successfully Deleted Files\n")
        f.write("| Filename | Original Location | Timestamp |\n")
        f.write("| :--- | :--- | :--- |\n")

        if deleted:
            for item in deleted:
                f.write(f"| {item['name']} | `{item['path']}` | {item['timestamp'].strftime('%Y-%m-%d %H:%M:%S')} |\n")
        else:
            f.write("| No files deleted | - | - |\n")

        f.write("\n## ⚠️ Files Not Found\n")
        f.write("| Filename | Status |\n")
        f.write("| :--- | :--- |\n")

        if not_found:
            for filename in not_found:
                f.write(f"| {filename} | Not found in Documents (already removed or moved) |\n")
        else:
            f.write("| All files located and deleted | - |\n")

        f.write("\n## 📝 Notes\n")
        f.write("- Master versions of all files have been preserved in `data/raw/` with V6 naming\n")
        f.write("- This deletion was executed after master file verification via `sniff_master_files.py`\n")
        f.write("- All deleted files were flagged as OUTDATED or DUPLICATE in the cleanup audit log\n\n")

        f.write("---\n*This log was automatically generated by the Deletion Sentinel.*\n")

    print(f"\n📝 Deletion report saved: {DELETION_LOG}")

if __name__ == "__main__":
    print("\n⚠️  WARNING: This will DELETE files permanently!")
    print("Proceeding in 2 seconds...\n")

    import time
    time.sleep(2)

    deleted, not_found = find_and_delete_deprecated()

    print("\n✅ Deletion process complete.")
