import os
import glob
import hashlib
import shutil
from pathlib import Path
from datetime import datetime

# 1. Configuration: Targeting your iMac User Folder
SOURCE_DIR = Path.home() / "Documents"
TARGET_DIR = Path.home() / "Documents/AILogbooks/data/raw"
LOG_DIR = Path.home() / "Documents/AILogbooks/logs"
CLEANUP_LOG_FILE = LOG_DIR / f"{datetime.now().strftime('%m-%d')}_LOGS_SYS_Cleanup-Audit_AILogbooks.md"
KEYWORDS = ['FileOrganizationDB', 'EdAssist', 'FLAIM', 'AI Index', 'Agents', 'FilenamingMasterDatabase']

def get_file_hash(filepath):
    """Generate MD5 hash to identify byte-for-byte duplicates."""
    hasher = hashlib.md5()
    with open(filepath, 'rb') as f:
        buf = f.read()
        hasher.update(buf)
    return hasher.hexdigest()

def generate_markdown_log(inventory_data):
    """Generates a human-readable audit trail of the file reorganization."""
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    with open(CLEANUP_LOG_FILE, 'w') as f:
        f.write(f"# 🧹 File Cleanup & Deprecation Audit\n")
        f.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"**Root:** ~/Documents/AILogbooks\n\n")

        f.write("## 🏆 Master Ingestion Summary\n")
        f.write("| Category | Master File Name | Status | Destination |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")

        for category, files in inventory_data.items():
            master = files[0]  # Assumes sorted by date
            f.write(f"| {category} | {master['name']} | ✅ MASTER | `data/raw/` |\n")

        f.write("\n## ⚠️ Deprecated & Duplicate Files\n")
        f.write("| Original Name | Category | Reason | Action Taken |\n")
        f.write("| :--- | :--- | :--- | :--- |\n")

        for category, files in inventory_data.items():
            if len(files) > 1:
                master_hash = files[0]['hash']
                for extra in files[1:]:
                    reason = "DUPLICATE" if extra['hash'] == master_hash else "OUTDATED VERSION"
                    f.write(f"| {extra['name']} | {category} | {reason} | Flagged for Deletion |\n")

        f.write("\n---\n*This log was automatically generated by the Integrity Sentinel.*")

    print(f"✅ Cleanup Log generated: {CLEANUP_LOG_FILE}")

def sniff_master_files():
    print(f"🔍 Sniffing {SOURCE_DIR} for Master Files...")

    all_files = []
    for keyword in KEYWORDS:
        found = glob.glob(str(SOURCE_DIR / f"**/*{keyword}*"), recursive=True)
        all_files.extend(found)

    # Filter out directories and the AILogbooks folder itself
    files_to_process = [f for f in all_files if os.path.isfile(f) and "AILogbooks" not in f]

    inventory = {}
    for f_path in files_to_process:
        path = Path(f_path)
        stats = path.stat()
        mtime = datetime.fromtimestamp(stats.st_mtime)
        f_hash = get_file_hash(f_path)

        category = next((k for k in KEYWORDS if k in path.name), "Unknown")
        if category not in inventory: inventory[category] = []

        inventory[category].append({
            "name": path.name, "path": f_path, "modified": mtime, "hash": f_hash
        })

    print("\n--- 📊 MASTER FILE ANALYSIS ---")
    masters_to_copy = []

    for category, files in inventory.items():
        files.sort(key=lambda x: x['modified'], reverse=True)
        master = files[0]
        print(f"✅ Category: {category} -> 🏆 Master: {master['name']}")
        masters_to_copy.append(master['path'])

        for extra in files[1:]:
            status = "DUPLICATE" if extra['hash'] == master['hash'] else "OUTDATED"
            print(f"      - {extra['name']} [{status}]")

    return masters_to_copy, inventory

if __name__ == '__main__':
    masters, inventory = sniff_master_files()

    # Generate cleanup audit log
    print("\n--- 📝 GENERATING AUDIT LOG ---")
    generate_markdown_log(inventory)

    # Copy master files to target directory
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    print("\n--- 🚀 COPYING MASTERS ---")
    for m in masters:
        shutil.copy(m, TARGET_DIR)
        print(f"✅ Ingested: {Path(m).name}")
